### ISSUE TITLE
web also ?

### ISSUE THREAD

**Issue by gedw99** [huffduff/go-indexeddb#1]
I heard about this on reddit at https://www.reddit.com/r/golang/comments/si3m9l/an_indexeddb_clone_in_pure_go/

Can you let me know if the intent is to also support web, like https://github.com/hack-pad/hackpadfs..

there is also this for web: https://github.com/paralin/go-indexeddb

**Comment by tommyo** [comment]
Thanks for pointing those out!

Both of those have the reverse goal of this project. They both wrap the browser's implementation of IndexedDB for use in Go, where this implements the IndexedDB api around a LevelDB implementation in Go.

Technically, it should be relatively simple to have either of them wrap this database, using native IndexedDB in WASM, and this database otherwise, thus exposing a consistent db api in any environment.

I'm currently working on a project that works the other way around - wrapping badgerdb in native go, and indexeddb for the web. That will likely be published here soon.

**Comment by gedw99** [comment]
hey @tommyo 

Ok let me know where the code is. 

Something was causing issue with https://github.com/syndtr/goleveldb

Genji used badgerdb and changed over to cockroachDB's pebble. I think they got problems with badgerdb, but i dont know.
They cross compiel to wasm with tinygo to have a inmemory db. they also compile to desktop and mobile.

https://github.com/genjidb/genji/blob/main/go.mod
https://github.com/cockroachdb/pebble
